config/routes.rb
Base::Application.routes.draw do
  get "password_resets/create"
  get "password_resets/edit"
  get "password_resets/update"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  
  
  get "cursosrealizados_menu_principal_profesor" => "cursosrealizados#menu_principal_profesor", :as => "cursosrealizados_menu_principal_profesor"
  get "secretariasis_menu_principal_secretaria" => "secretariasis#menu_principal_secretaria", :as => "secretariasis_menu_principal_secretaria"
  get "buscar_distributivos" => "secretariasis#result_busqueda", :as => "buscar_distributivos" 
  
  get "secretarias_menu_principal_secretaria" => "secretarias#menu_principal_secretaria", :as => "secretarias_menu_principal_secretaria"
  
  get "buscar_mallas" => "secretariasis#result_busquedamalla", :as => "buscar_mallas"

  get "result_buscar" => "secretariasis#buscar", :as => "result_buscar"
  get "activar" => "secretariasis#activar", :as => "activar"
  get "validar" => "secretariasis#validar", :as => "validar"
  get "edit_matr_alum" => "secretariasis#edit_matr_alum", :as => "edit_matr_alum"
  get "update_matr_alum" => "secretariasis#update_matr_alum", :as => "update_matr_alum"

  get "buscar_estudiantes" => "secretariasis#result_estud", :as => "buscar_estudiantes"
  get "estudiantes_curso" => "secretariasis#estudiantes_curso", :as => "estudiantes_curso"
  
  get "estudiantes_estado" => "secretariasis#estudiantes_estado", :as => "estudiantes_estado"
  get "buscar_estado" => "secretariasis#result_estud_estado", :as => "buscar_estado"
  
  
  
   get "matriculasacademicas_menu_principal_alumno" => "matriculasacademicas#menu_principal_alumno", :as => "matriculasacademicas_menu_principal_alumno"
   
  
   get "index_menu_principal_admin" => "index#menu_principal_admin", :as => "index_menu_principal_admin"
  
  
  get "asignaturas_menu_principal_admin" => "asignaturas#menu_principal_admin", :as => "asignaturas_menu_principal_admin"
  get "asignaturas_menu_principal_admin_index" => "asignaturas#menu_principal_admin_index", :as => "asignaturas_menu_principal_admin_index"
  get "asignaturas_edit" => "asignaturas#menu_principal_admin_edit", :as => "asignaturas_menu_principal_admin_edit"
      
  
  get "secciones_menu_principal_admin" => "secciones#menu_principal_admin", :as => "secciones_menu_principal_admin"
  get "secciones_edit" => "secciones#menu_principal_admin_edit", :as => "secciones_menu_principal_admin_edit" 
  
   
  get "lectivos_menu_principal_admin" => "lectivos#menu_principal_admin", :as => "lectivos_menu_principal_admin"   
  get "niveles_menu_principal_admin" => "niveles#menu_principal_admin", :as => "niveles_menu_principal_admin"   
  get "tipomallas_menu_principal_admin" => "tipomallas#menu_principal_admin", :as => "tipomallas_menu_principal_admin"  
  get "mallacurriculares_menu_principal_admin" => "mallacurriculares#menu_principal_admin", :as => "mallacurriculares_menu_principal_admin"
  
  get "tiponiveles_menu_principal_admin" => "tiponiveles#menu_principal_admin", :as => "tiponiveles_menu_principal_admin"
    
  get "paralelos_menu_principal_admin" => "paralelos#menu_principal_admin", :as => "paralelos_menu_principal_admin"
  
  get "promotions_menu_principal_admin" => "promotions#menu_principal_admin", :as => "promotions_menu_principal_admin"  
  
  get "malla_asignar" => "mallacurriculares#asignar", :as => "malla_asignar"
  get "malla_eliminar" => "mallacurriculares#destroy", :as => "malla_eliminar"
        
  get "asignaturas/index"
  get "asignaturas/edit" 
  get "asignaturas/show" 

  get "secciones/index"
  get "secciones/edit" 
  get "secciones/show" 
  
  get "lectivos/index"
  get "lectivos/edit" 
  get "lectivos/show" 
  
  
  get "niveles/index"
  get "niveles/edit" 
  get "niveles/show"
  get "niveles/new"
  get "niveles/create"
      
  get "cursosrealizados/index"
  get "cursosrealizados/new"
  get "cursosrealizados/edit" 
  get "cursosrealizados/show"
  get "cursosrealizados/horario"
  
  get "secretarias/ind_distr"
  
  
  get "secretarias/curriculsecretari"
  get "secretarias/new"
  get "secretarias/edit" 
  get "secretarias/show"
  get "secretariasis/buscar"
  get "secretariasis/result_buscar"

  
  get "tipomallas/index"
  get "tipomallas/edit" 
  get "tipomallas/show"
  
  get "mallacurriculares/index"
  get "mallacurriculares/edit" 
  get "mallacurriculares/show"
  get "mallacurriculares/new"
  get "mallacurriculares/create"
  get "mallacurriculares/update"
  
  get "tiponiveles/index"
  get "tiponiveles/edit" 
  get "tiponiveles/show"
  
  get "paralelos/index"
  get "paralelos/edit" 
  get "paralelos/new"
  get "paralelos/update"
  get "paralelos_index" => "paralelos#index", :as => "paralelos_index"
  
  get "datosalumnos/index" 
  get "datosalumnos/edit"
  
  get "promotions/index"
  get "promotions/edit" 
  get "promotions/new"
  
  get "distributos/index"
  get "distributos/update"
  get "distributos/edit" 
  get "distributos/new"
  get "distributos/update_niveles", :as => "update_niveles"
  get "distributos/update_asignaturas", :as => "update_asignaturas"
  get "distributos/update_cursos", :as => "update_cursos"
  get "distributos_new" => "distributos#new", :as => "distributos_new"
  get "distributos_index" => "distributos#index", :as => "distributos_index"  
  get "distributos_menu_principal_admin" => "distributos#menu_principal_admin", :as => "distributos_menu_principal_admin"

  
  post "mallactual" => "mallacurriculares#update", :as => "mallactual"
  post "datoseditalum" => "datosalumnos#update", :as => "datoseditalum"
  
  get "matriculasacademicas_new" => "matriculasacademicas#new", :as => "matriculasacademicas_new"

  get "matriculasacademicas_imprimir" => "matriculasacademicas#imprimir", :as => "matriculasacademicas_imprimir"
  
  get "matriculasacademicas/new"
  get "matriculasacademicas/index"
  get "matriculasacademicas/show"  
  
  get "notasasacademicas/new"
  get "notasacademicas/index"
  get "notasasacademicas/consultas_correo"  
  
  get "cursosprofesores/new"
  get "cursosprofesores/index"
  get "cursosprofesores/show"
  get "cursosprofesores/alumnos"
  get "cursosprofesores/edit"
  get "cursosprofesores/update"
  get "cursosprofesores/lista"
    
  get "alumnos_matriculados_lista" => "cursosprofesores#imprimir_lista", :as => "alumnos_matriculados_lista"
  
  get "alumnos_matriculados" => "cursosprofesores#new", :as => "alumnos_matriculados"
  get "edit_alumnos_matriculados" => "cursosprofesores#edit", :as => "edit_alumnos_matriculados"
  post "update_alumnos_matriculados" => "cursosprofesores#update", :as => "update_alumnos_matriculados"
  

  resources :users
  resources :sessions
  resources :asignaturas  
  resources :secciones
  resources :lectivos
  resources :niveles

  resources :personas
  
  resources :cursosrealizados
  resources :secretarias
  resources :tipomallas
  resources :tiponiveles
  resources :mallacurriculares
  resources :paralelos
  resources :promotions
  resources :distributos
  resources :cursosprofesores
  
  resources :notasacademicas
    
  resources :password_resets
  
  

  

  
   root :to => 'index#menu_principal'

  match ':controller(/:action(/:id))(.:format)'
  match '/asignaturas/:id', :to => 'asignaturas#show', :as => :asignatura 
  match '/secciones/:id', :to => 'secciones#show', :as => :seccion
  match '/lectivos/:id', :to => 'lectivos#show', :as => :periodo 
  match '/niveles/:id', :to => 'niveles#show', :as => :nivel
      
  match '/cursosrealizados/:id', :to => 'cursosrealizados#edit', :as => :estudio
  match '/cursosrealizados/:id', :to => 'cursosrealizados#edit', :as => :laboral
  
  
  match '/tipomallas/:id', :to => 'tipomallas#show', :as => :clase
  match '/tiponiveles/:id', :to => 'tiponiveles#show', :as => :nivele
  match '/mallacurriculares/:id', :to => 'mallacurriculares#show', :as => :malla
  match '/paralelos/:id', :to => 'paralelos#show', :as => :curso

  match '/distributos/:id', :to => 'distributos#show', :as => :distributivo
  match '/users/:id', :to => 'users#index', :as => :user
  match '/matriculasacademicas/:id', :to => 'matriculasacademicas#show', :as => :matricula
  match '/cursosprofesores/:id', :to => 'cursosprofesores#show', :as => :calificacione
  
  match '/secretarias/:id', :to => 'secretarias#result_busquedaestud', :as => :persona
end

app/models/nivele.rb
class Nivele < ActiveRecord::Base
  
  
  has_many :nivels
  attr_accessible :tip_niv_nombre
  
  
   validates :tip_niv_nombre, presence: true
   validates_uniqueness_of :tip_niv_nombre
  
end

app/controllers/niveles_controller.rb
class NivelesController < ApplicationController
  
#before_filter :require_login, :only => [:new, :edit, :destroy, :show, :index] # => CONTROLO QUE EL USUARO NO PUEDA VER NADA DE ESTO
#load_and_authorize_resource :only => [:new, :edit, :destroy] CON ESTO DIGO QUE "NO PUEDE VER EL CONTENIDO"
  before_filter :require_login, :only => [:new, :edit, :destroy, :show, :index]
  before_filter :authenticated_admin 
  
  def index
    @nivel= Nivel.find(:all)
    @nivele= Nivele.find(:all)
  end
  
  
  def new
    @nivel= Nivel.new
    @nivele = Nivele.find(:all)
   # @nivele= Nivele.new
  end
     
  
  def create
    @nivel = Nivel.new(params[:nivel])
    #@nivele = Nivel.new(params[:nivele])
       if @nivel.save 
       #if @nivel.save and @nivele.save
    redirect_to niveles_menu_principal_admin_path,  :notice => 'CURSO CREADO CON EXITO'
   end
  end
    
   
  
  def show 
    @nivels = Nivel.find(params[:id])
  end

   
   def destroy
    @nivel= Nivel.find(params[:id])
    @nivel.destroy
    redirect_to niveles_menu_principal_admin_path
  end
   
   
   def edit 
   @nivels= Nivel.find(params[:id])
   
    end
    
   
   def update
     @nivel= Nivel.find (params[:id])
     @nivel.update_attributes(params[:nivel])
     redirect_to niveles_menu_principal_admin_path
   end
end

app/helpers/niveles_helper.rb
module NivelesHelper
end

app/views/niveles/create.erb
<% if @nivel.errors.any? %>

            <div align="left">             
                <ul><H1><font SIZE="4" FACE="arial" color ="#BF0000"> ERRORES</font>      </H1>      
                  <% for message in @nivel.errors.full_messages %>                          
                    <li><%= message %></li>
                    <br> 
                 <% end %>
                </ul>              
            </div>
          <% end %>


app/views/niveles/edit.erb
<%=form_for @nivels do |f| %>
  
<p>
  <%=f.label "NIVEL"%>
  <%=f.text_field :nivel_numero %>
</p>

 
<p>
  <%=f.label "DESCRIPCION"%>
  <%=f.text_field :nivel_descrip %>
</p>

<%=  f.submit "GUARDAR" %>
<%end%>

app/views/niveles/index.erb
<h1>CURSOS CREADOS EN RUBY ON RAILS!!!</h1>
<% @nivel.each do |f| %>
<p>
<%=f.nivel_numero %> 
<%=f.nivel_descrip %>****
<%=f.nivele.tip_niv_nombre %>
<%= link_to "EDITAR", edit_nivele_path(f) %>   
<%= link_to "MOSTRAR", f %>  
<%= link_to "ELIMINAR", f, :confirm => 'ESTAS SEGURISIMO ??', :method => :delete %>

</p>
<%end%>

    

app/views/niveles/menu_principal_admin.erb
<html>
<head>
<%#=javascript_include_tag 'cycle.js'%>
<%#=stylesheet_link_tag 'index.css', :media => "screen" %>
<%#*<script type="text/javascript">$('#rotator').cycle('fade');%>
</script>
<title>AJAX: actualizar contenido</title>
<link href="style.css" rel="stylesheet" type="text/css" />
<link href="index.scss" rel="stylesheet" type="text/css" />
<script language="JavaScript" type="text/javascript" src="ajax.js"></script>
</head>    
       <head>         
         <style>
<!--
.styling{
background-color:black;
color:lime;
font: bold 16px MS Sans Serif;
padding: 3px;
}
-->
</style>         
       </head>       
       <body id="reloj">         
         <span id="digitalclock" class="styling"></span>
<script>
  
<!--
//HORA DEL SISTEMA EN VIVO
var alternate=0
var standardbrowser=!document.all&&!document.getElementById

if (standardbrowser)
document.write('<form name="tick"><input type="text" name="tock" size="11"></form>')

function show(){
if (!standardbrowser)
var clockobj=document.getElementById? document.getElementById("digitalclock") : document.all.digitalclock
var Digital=new Date()
var hours=Digital.getHours()
var minutes=Digital.getMinutes()
var dn="AM"

if (hours==12) dn="PM" 
if (hours>12){
dn="PM"
hours=hours-12
}
if (hours==0) hours=12
if (hours.toString().length==1)
hours="0"+hours
if (minutes<=9)
minutes="0"+minutes

if (standardbrowser){
if (alternate==0)
document.tick.tock.value=hours+" : "+minutes+" "+dn
else
document.tick.tock.value=hours+"   "+minutes+" "+dn
}
else{
if (alternate==0)
clockobj.innerHTML=hours+" : "+minutes+" "+"<sup style='font-size:1px'>"+dn+"</sup>"
else
clockobj.innerHTML=hours+" : "+minutes+" "+"<sup style='font-size:1px'>"+dn+"</sup>"
}
alternate=(alternate==0)? 1 : 0
setTimeout("show()",1000)
}
window.onload=show
//-->
</script>
         
         
         <script language="JavaScript">
<!--
// ==============================================
// FECHA MES, DIA, AÑO
var TheFontFace  = "algerian";
var TheFontColor = "#1656C4";
var TheFontSize  = "4";
var TheFontStyle = "boldcastellar"; 

// Set the separator between the date elements;
// usually use either - or /.

var TheSeparator = "-";

// Show or do not show the day of the week; set
// yes to show, no not to show.

var ShowDay ="yes";
// Do Not Edit Below This Line
// ==============================================
var Days = new Array("Domingo","Lunes","Martes","Miercoles","Jueves","Viernes","Sabado");
var TheDate = new Date();

var TheWeekDay = TheDate.getDay();
var Day ="";
if (ShowDay == "yes"){
    Day = Days[TheWeekDay];
    Day += " ";}

var TheMonth = TheDate.getMonth() + 1;
if (TheMonth < 10) TheMonth = "0" + TheMonth;

var TheMonthDay = TheDate.getDate();
if (TheMonthDay < 10) TheMonthDay = "0" + TheMonthDay;

var TheYear = TheDate.getYear();
if (TheYear < 1000) TheYear += 1900;

var FontTagLeft  = "";
var FontTagRight = "";

if (TheFontStyle == "bold"){
    FontTagLeft = "<b>";
    FontTagRight ="</b>";}
    
if (TheFontStyle == "castellar"){
    FontTagLeft = "<i>";
    FontTagRight ="</i>";}
    
if (TheFontStyle == "boldcastellar"){
    FontTagLeft = "<b><i>"; 
    FontTagRight = "</i></b>";}    

var D = "";
D += "<font color='"+TheFontColor+"' face='"+TheFontFace+"' size='"+TheFontSize+"'>";
D += FontTagLeft+Day+TheMonth+TheSeparator+TheMonthDay+TheSeparator+TheYear+FontTagRight;
D += "</font>";
document.write(D);
//-->
</script>        
</body>
       <%if current_user%>
       <div align="right">                
   <font color="#0073FF" FACE="arial"><b><%= current_user.email%></b></font>
       </div>

       <%end%>
 
  <body id="body2">        
    <div align="left">                                 
<b><font color ="#D101DC" FACE="roman"></b></f>  
    </div>      
    
    <%if current_user%>
    <div align="right"> 
      <font FACE="roman" ><b><%= link_to "Cerrar Sesión", logout_path %></b></font>
    </div>
    <%end%>
    
    
    <%if current_user%>
    <%else%>
    <div align="right">
    <%= link_to "INICIE SESIÓN", login_path %>
    </div>
    <%end%>        
    <HR noshade size="8" width="100%">  

    
    
       

  <%if current_user%> 
  <%else%>
<div id ="rotator">
<img align="right" <%=image_tag "pa3.jpg"%></img>
<img align="right" <%=image_tag "pa4.jpg"%></img>
<img align="right" <%=image_tag "papin.jpeg"%></img>
<img align="right" <%=image_tag "an1.jpg"%></img>
<img align="right" <%=image_tag "an2.jpg"%></img>
<img align="right" <%=image_tag "an3.jpg"%></img>
<img align="right" <%=image_tag "an4.jpg"%></img>
<img align="right" <%=image_tag "an5.jpg"%></img>
<img align="right" <%=image_tag "an6.jpg"%></img>
<img align="right" <%=image_tag "an7.jpg"%></img>
<img align="right" <%=image_tag "an8.jpg"%></img>
<img align="right" <%=image_tag "an9.jpg"%></img>
<img align="right" <%=image_tag "an10.jpg"%></img>
<img align="right" <%=image_tag "an12.jpg"%></img>
<img align="right" <%=image_tag "an13.jpg"%></img>
<img align="right" <%=image_tag "an14.jpg"%></img>
<img align="right" <%=image_tag "an15.jpg"%></img>
</div>
     <%end%>  
 
    
    
    
    <div align="center">                                  
      <p><font color="#1C2ACB" SIZE="6" FACE="algerian"><b>UNIDAD EDUCATIVA PARTICULAR MIXTA</b></font> <font color="#230000" SIZE="6" FACE="algerian"><b>"JUAN PABLO II"</b></font></p>
    </div>
    
    
    
           <div align="right">                                                      
           <div id="container">
<div align="right" class="user_nav">
<%= link_to "CREAR USUARIO", signup_path %>
</div>           
           </div>              
           </div>  
    
    
    
    
  <ul id="navidad">   
    
  <%if current_user%>
  <li><a href="#"><font FACE="LUCIDA CONSOLE" color="C13131" size="2"><b>ASIGNATURA</b></font></a>
                  <ul>
                    <li><a href="javascript:Solicitud('asignaturas/new.html','pagina')"> <b>CREAR ASIGNATURA</b></a></li>                       
                    <li><a href="javascript:Solicitud('asignaturas/index.html','pagina')">  <b>LISTE ASIGNATURAS</b></a></li>                    
                  </ul>                             
  </li>

   
 
  <li><a href="#"><font FACE="LUCIDA CONSOLE" color="C13131" size="2"><b>SECCIÓN</b></font></a>
                  <ul>
                     <li><a href="javascript:Solicitud('secciones/new.html','pagina')"><b>CREAR SECCION</b></a></li>
                     <li><a href="javascript:Solicitud('secciones/index.html','pagina')">  <b>LISTE SECCIONES</b></a></li>                        
                  </ul>
  </li>
  
  
  
  <li><a href="#"><font FACE="LUCIDA CONSOLE" color="C13131" size="2"><b>CURSO</b></font></a>
                  <ul>
                    <li><a href="javascript:Solicitud('niveles/new.html','pagina')"><b>CREAR CURSO</b></a></li>
                    <li><a href="javascript:Solicitud('niveles/index.html','pagina')"><b>LISTAR CURSOS</b></a></li>                                        
                  </ul>
  </li>  
  
  
  <li><a href="#"><font FACE="LUCIDA CONSOLE" color="C13131" size="2"><b>T. CURSO</b></font></a>
                  <ul>
                    <li><a href="javascript:Solicitud('tiponiveles/new.html','pagina')"><b>Crear T. NIVEL</b></a></li>
                    <li><a href="javascript:Solicitud('tiponiveles/index.html','pagina')"><b>Listar T. NIVEL</b></a></li>
                  </ul>
  </li>

  
  
   
  <li><a href="#"><font FACE="LUCIDA CONSOLE" color="C13131" size="2"><b>P.LECTIVO</b></font></a>
                  <ul>
                    <li><a href="javascript:Solicitud('lectivos/new.html','pagina')"><b>Crear P. Lectivo</b></a></li>
                    <li><a href="javascript:Solicitud('lectivos/index.html','pagina')"><b>Listar P. Lectivo</b></a></li>
                  </ul>
  </li>
   
  
  
  <li><a href="#"><font FACE="LUCIDA CONSOLE" color="C13131" size="2"><b>T.MALLAS</b></font></a>
                  <ul>
                    <li><a href="javascript:Solicitud('tipomallas/new.html','pagina')"><b>Crear tipos de Mallas</b></a></li>
                    <li><a href="javascript:Solicitud('tipomallas/index.html','pagina')"><b>Listar tipos de Mallas</b></a></li>
                  </ul>
  </li>
  
  
  <li><a href="#"><font FACE="LUCIDA CONSOLE" color="C13131" size="2"><b>MALLA</b></font></a>
                  <ul>
                    <li><a href="javascript:Solicitud('mallacurriculares/new.html','pagina')"><b>CREAR MALLA</b></a></li>
                    <li><a href="javascript:Solicitud('mallacurriculares/index.html','pagina')"><b>LISTAR MALLA</b></a></li>
                  </ul>
  </li>
  
  
  <%#*<li><a href="#"><font FACE="LUCIDA CONSOLE" color="C13131" size="2"><b>PROMOCION</b></font></a>%>
                  <%#*<ul>%>
                     <%#*<li><a href="javascript:Solicitud('promotions/new.html','pagina')"><b>CREAR PROMOCION</b></a></li>%>                    
                     <%#*<li><a href="javascript:Solicitud('promotions/index.html','pagina')"><b>LISTAR PROMOCIONES</b></a></li>%>
                  <%#*</ul>%>
   <%#*</li>%>
 
  
  
  <li><a href="#"><font FACE="LUCIDA CONSOLE" color="C13131" size="2"><b>PARALELO</b></font></a>
                  <ul>
                    <li><a href="javascript:Solicitud('paralelos/new.html','pagina')"><b>CREAR PARALELO</b></a></li>
                    <%#*<li><a href="javascript:Solicitud('paralelos/index.html','pagina')"><b>LISTAR</b></a></li>%>
                     <li><%= link_to 'LISTAR PARALELOS', paralelos_index_path %></li>
                  </ul>
  </li>
  
    <li><a href="#"><font FACE="LUCIDA CONSOLE" color="C13131" size="2"><b>DISTRIBUTIVO</b></font></a>
                   <ul>
                    <li><%= link_to 'Distributivo', distributos_new_path %></li>
                    <li><%= link_to 'Listar Distributivo', distributos_index_path %></li>
                    <%#*<li><a href="javascript:Solicitud('distributos/index.html','pagina')"><b>LISTAR DISTRIBUTIVO</b></a></li>%>                   
                   </ul>
  </li>
  
  
  <%end%>
  </ul>   
   
   
   
   <div id="contenedor">
	<div id="navidad">		
	</div>
	<div id="pagina"></div>
</div>
 </body>
  </html> 

app/views/niveles/new.erb
<%=form_for @nivel , :url => {:action=>"create"} do |f| %>
   
<p>
  <%=f.label "NIVEL"%>
  <%=f.text_field :nivel_numero %>
</p>

 
<p>
  <%=f.label "DESCRIPCION"%>
  <%=f.text_field :nivel_descrip %>
</p>

<table>
 <% @nivele.each do |n| %>
<tr>
  
  <td> <%= f.radio_button :nivele_id, n.id%> <%=  n.tip_niv_nombre %></td>
</tr>
 <% end %>
</table>
<%=  f.submit "GUARDAR" %>
<%end%>

app/views/niveles/show.erb
    <%= notice %>
<h1><%= @nivels.nivel_numero %></h1>
<br><%= @nivels.nivel_descrip %><br/>

app/views/niveles/update.erb
ACTUALIZADO CORRECTAMENTE EL REGISTRO