config/routes.rb
Base::Application.routes.draw do
  get "password_resets/create"
  get "password_resets/edit"
  get "password_resets/update"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  
  
  get "cursosrealizados_menu_principal_profesor" => "cursosrealizados#menu_principal_profesor", :as => "cursosrealizados_menu_principal_profesor"
  get "secretariasis_menu_principal_secretaria" => "secretariasis#menu_principal_secretaria", :as => "secretariasis_menu_principal_secretaria"
  get "buscar_distributivos" => "secretariasis#result_busqueda", :as => "buscar_distributivos" 
  
  get "secretarias_menu_principal_secretaria" => "secretarias#menu_principal_secretaria", :as => "secretarias_menu_principal_secretaria"
  
  get "buscar_mallas" => "secretariasis#result_busquedamalla", :as => "buscar_mallas"

  get "result_buscar" => "secretariasis#buscar", :as => "result_buscar"
  get "activar" => "secretariasis#activar", :as => "activar"
  get "validar" => "secretariasis#validar", :as => "validar"
  get "edit_matr_alum" => "secretariasis#edit_matr_alum", :as => "edit_matr_alum"
  get "update_matr_alum" => "secretariasis#update_matr_alum", :as => "update_matr_alum"

  get "buscar_estudiantes" => "secretariasis#result_estud", :as => "buscar_estudiantes"
  get "estudiantes_curso" => "secretariasis#estudiantes_curso", :as => "estudiantes_curso"
  
  get "estudiantes_estado" => "secretariasis#estudiantes_estado", :as => "estudiantes_estado"
  get "buscar_estado" => "secretariasis#result_estud_estado", :as => "buscar_estado"
  
  
  
   get "matriculasacademicas_menu_principal_alumno" => "matriculasacademicas#menu_principal_alumno", :as => "matriculasacademicas_menu_principal_alumno"
   
  
   get "index_menu_principal_admin" => "index#menu_principal_admin", :as => "index_menu_principal_admin"
  
  
  get "asignaturas_menu_principal_admin" => "asignaturas#menu_principal_admin", :as => "asignaturas_menu_principal_admin"
  get "asignaturas_menu_principal_admin_index" => "asignaturas#menu_principal_admin_index", :as => "asignaturas_menu_principal_admin_index"
  get "asignaturas_edit" => "asignaturas#menu_principal_admin_edit", :as => "asignaturas_menu_principal_admin_edit"
      
  
  get "secciones_menu_principal_admin" => "secciones#menu_principal_admin", :as => "secciones_menu_principal_admin"
  get "secciones_edit" => "secciones#menu_principal_admin_edit", :as => "secciones_menu_principal_admin_edit" 
  
   
  get "lectivos_menu_principal_admin" => "lectivos#menu_principal_admin", :as => "lectivos_menu_principal_admin"   
  get "niveles_menu_principal_admin" => "niveles#menu_principal_admin", :as => "niveles_menu_principal_admin"   
  get "tipomallas_menu_principal_admin" => "tipomallas#menu_principal_admin", :as => "tipomallas_menu_principal_admin"  
  get "mallacurriculares_menu_principal_admin" => "mallacurriculares#menu_principal_admin", :as => "mallacurriculares_menu_principal_admin"
  
  get "tiponiveles_menu_principal_admin" => "tiponiveles#menu_principal_admin", :as => "tiponiveles_menu_principal_admin"
    
  get "paralelos_menu_principal_admin" => "paralelos#menu_principal_admin", :as => "paralelos_menu_principal_admin"
  
  get "promotions_menu_principal_admin" => "promotions#menu_principal_admin", :as => "promotions_menu_principal_admin"  
  
  get "malla_asignar" => "mallacurriculares#asignar", :as => "malla_asignar"
  get "malla_eliminar" => "mallacurriculares#destroy", :as => "malla_eliminar"
        
  get "asignaturas/index"
  get "asignaturas/edit" 
  get "asignaturas/show" 

  get "secciones/index"
  get "secciones/edit" 
  get "secciones/show" 
  
  get "lectivos/index"
  get "lectivos/edit" 
  get "lectivos/show" 
  
  
  get "niveles/index"
  get "niveles/edit" 
  get "niveles/show"
  get "niveles/new"
  get "niveles/create"
      
  get "cursosrealizados/index"
  get "cursosrealizados/new"
  get "cursosrealizados/edit" 
  get "cursosrealizados/show"
  get "cursosrealizados/horario"
  
  get "secretarias/ind_distr"
  
  
  get "secretarias/curriculsecretari"
  get "secretarias/new"
  get "secretarias/edit" 
  get "secretarias/show"
  get "secretariasis/buscar"
  get "secretariasis/result_buscar"

  
  get "tipomallas/index"
  get "tipomallas/edit" 
  get "tipomallas/show"
  
  get "mallacurriculares/index"
  get "mallacurriculares/edit" 
  get "mallacurriculares/show"
  get "mallacurriculares/new"
  get "mallacurriculares/create"
  get "mallacurriculares/update"
  
  get "tiponiveles/index"
  get "tiponiveles/edit" 
  get "tiponiveles/show"
  
  get "paralelos/index"
  get "paralelos/edit" 
  get "paralelos/new"
  get "paralelos/update"
  get "paralelos_index" => "paralelos#index", :as => "paralelos_index"
  
  get "datosalumnos/index" 
  get "datosalumnos/edit"
  
  get "promotions/index"
  get "promotions/edit" 
  get "promotions/new"
  
  get "distributos/index"
  get "distributos/update"
  get "distributos/edit" 
  get "distributos/new"
  get "distributos/update_niveles", :as => "update_niveles"
  get "distributos/update_asignaturas", :as => "update_asignaturas"
  get "distributos/update_cursos", :as => "update_cursos"
  get "distributos_new" => "distributos#new", :as => "distributos_new"
  get "distributos_index" => "distributos#index", :as => "distributos_index"  
  get "distributos_menu_principal_admin" => "distributos#menu_principal_admin", :as => "distributos_menu_principal_admin"

  
  post "mallactual" => "mallacurriculares#update", :as => "mallactual"
  post "datoseditalum" => "datosalumnos#update", :as => "datoseditalum"
  
  get "matriculasacademicas_new" => "matriculasacademicas#new", :as => "matriculasacademicas_new"

  get "matriculasacademicas_imprimir" => "matriculasacademicas#imprimir", :as => "matriculasacademicas_imprimir"
  
  get "matriculasacademicas/new"
  get "matriculasacademicas/index"
  get "matriculasacademicas/show"  
  
  get "notasasacademicas/new"
  get "notasacademicas/index"
  get "notasasacademicas/consultas_correo"  
  
  get "cursosprofesores/new"
  get "cursosprofesores/index"
  get "cursosprofesores/show"
  get "cursosprofesores/alumnos"
  get "cursosprofesores/edit"
  get "cursosprofesores/update"
  get "cursosprofesores/lista"
    
  get "alumnos_matriculados_lista" => "cursosprofesores#imprimir_lista", :as => "alumnos_matriculados_lista"
  
  get "alumnos_matriculados" => "cursosprofesores#new", :as => "alumnos_matriculados"
  get "edit_alumnos_matriculados" => "cursosprofesores#edit", :as => "edit_alumnos_matriculados"
  post "update_alumnos_matriculados" => "cursosprofesores#update", :as => "update_alumnos_matriculados"
  

  resources :users
  resources :sessions
  resources :asignaturas  
  resources :secciones
  resources :lectivos
  resources :niveles

  resources :personas
  
  resources :cursosrealizados
  resources :secretarias
  resources :tipomallas
  resources :tiponiveles
  resources :mallacurriculares
  resources :paralelos
  resources :promotions
  resources :distributos
  resources :cursosprofesores
  
  resources :notasacademicas
    
  resources :password_resets
  
  

  

  
   root :to => 'index#menu_principal'

  match ':controller(/:action(/:id))(.:format)'
  match '/asignaturas/:id', :to => 'asignaturas#show', :as => :asignatura 
  match '/secciones/:id', :to => 'secciones#show', :as => :seccion
  match '/lectivos/:id', :to => 'lectivos#show', :as => :periodo 
  match '/niveles/:id', :to => 'niveles#show', :as => :nivel
      
  match '/cursosrealizados/:id', :to => 'cursosrealizados#edit', :as => :estudio
  match '/cursosrealizados/:id', :to => 'cursosrealizados#edit', :as => :laboral
  
  
  match '/tipomallas/:id', :to => 'tipomallas#show', :as => :clase
  match '/tiponiveles/:id', :to => 'tiponiveles#show', :as => :nivele
  match '/mallacurriculares/:id', :to => 'mallacurriculares#show', :as => :malla
  match '/paralelos/:id', :to => 'paralelos#show', :as => :curso

  match '/distributos/:id', :to => 'distributos#show', :as => :distributivo
  match '/users/:id', :to => 'users#index', :as => :user
  match '/matriculasacademicas/:id', :to => 'matriculasacademicas#show', :as => :matricula
  match '/cursosprofesores/:id', :to => 'cursosprofesores#show', :as => :calificacione
  
  match '/secretarias/:id', :to => 'secretarias#result_busquedaestud', :as => :persona
end

app/controllers/secretariasis_controller.rb
class SecretariasisController < ApplicationController
 before_filter :require_login, :only => [:new, :edit, :destroy, :show, :index]
 before_filter :authenticated_secreta
 
  
 
  
   helper_method :sort_column, :sort_direction
 
   def index 
    @estudio = Estudio.where(:persona_id => current_user.persona.id)
    @laboral = Laboral.where(:persona_id => current_user.persona.id)    
   end
   
  def new
    @estudio= Estudio.new
    @laboral= Laboral.new
  end

  
  
  
  
  
  
  
  
# BUSCAR DISTRIBUTIVO POR PERIODO LECTIVO  
  def ind_distr
    @periodos = Periodo.find(:all)
  end

  def result_busqueda
    @periodos = Periodo.where('period_fech_ini LIKE ?', params[:fecha_inicio]) unless params[:fecha_inicio].blank?
    @periodos = @periodos.where('period_fech_fin LIKE ?', params[:fecha_fin]) unless params[:fecha_fin].blank?
  end
  
  
  
  
  
# BUSCAR MALLAS CURRICULARES POR PERIODO LECTIVO
  def ind_mall
  @periodos_count = Periodo.count()
   if @periodos_count > 1
     @ultimo_periodo = Periodo.find(:last)
   else
     @ultimo_periodo = Periodo.find(:first)
   end
   
   @mallas = Malla.where(:mall_fech_fin => @ultimo_periodo.period_fech_fin)
  end
  
  def result_busquedamalla  
    @mallas = Malla.where('mall_fech_inic LIKE ?', params[:fecha_inicio]) unless params[:fecha_inicio].blank?
    @mallas = @mallas.where('mall_fech_fin LIKE ?', params[:fecha_fin]) unless params[:fecha_fin].blank?   
  end


  def buscar
    if params[:cedula_estudiante]==nil
      @estudiante = nil
      @usuario = nil
      @matricula = nil
      @representante = nil
    else
      @estudiante = Persona.find_by_pers_cedula(params[:cedula_estudiante])
      @usuario = User.find_by_persona_id(@estudiante.id)
      @matricula = Matricula.where(:persona_id=>@estudiante.id).last
      @representante = Persona.joins(:representantes).where(:representantes=>{:estudiante_id =>@estudiante.id}).first
    end
  end

  def activar
    usuario = User.joins(:persona).where(:personas=>{:id=>params[:estudiante]}).first
    User.find(usuario.id).update_attributes(usu_estado: "A")
    redirect_to secretariasis_menu_principal_secretaria_path
  end

  def validar
    matricula = Matricula.where(:persona_id => params[:estudiante]).last
    Matricula.find(matricula).update_attributes(matr_estado: "V")
    redirect_to secretariasis_menu_principal_secretaria_path
  end

  def edit_matr_alum
    periodo_last = Periodo.last
    @cursos_last = Curso.where(:periodo_id=>periodo_last.id)
    @persona = Persona.find(params[:estudiante])
  end

  def update_matr_alum
    matricula = Matricula.where(:persona_id => params[:estudiante_id]).last
    Matricula.find(matricula).update_attributes(curso_id: params[:curso_id])
    persona = Persona.find(params[:estudiante_id])
    redirect_to result_buscar_path(:cedula_estudiante=>persona.pers_cedula)
  end

  
  
#BUSCAR ALUMNO POR MEDIO DE LA CEDULA Y VER SUS NOTAS 
#FALTAAAAAAAAAAAAAAAAA
#  def result_busquedapers
#    @personas = Persona.where('pers_cedula LIKE ?', params[:persona_cedula]) unless params[:persona_cedula].blank?
#    @mallas = @mallas.where('mall_fech_fin LIKE ?', params[:fecha_fin]) unless params[:fecha_fin].blank?
#  end
#  
#  def ind_perso
#    @personas = Persona.find(:all)
#  end

  
  
  
  
  
  

#BUSCAR LISTA DE ALUMNOS EN TODOS LOS CURSOS POR MEDIO DEL PERIODO LECTIVO
  def ind_estud
    #@periodos = Periodo.find(:all)
  end

  def result_estud
    @periodos = Periodo.where('period_fech_ini LIKE ?', params[:fecha_inicio]) unless params[:fecha_inicio].blank?
    @periodos = @periodos.where('period_fech_fin LIKE ?', params[:fecha_fin]) unless params[:fecha_fin].blank?
  end

  
  
  
  def estudiantes_curso
    curso_id = params[:curso_id]
    @estudiantes = Persona.joins(:matriculas).where(:matriculas => {:curso_id => curso_id})
  end
  
  
  
  
  
  def ind_estud_estado
    #@periodos = Periodo.find(:all)
  end


  def result_estud_estado
    @periodos = Periodo.where('period_fech_ini LIKE ?', params[:fecha_inicio]) unless params[:fecha_inicio].blank?
    @periodos = @periodos.where('period_fech_fin LIKE ?', params[:fecha_fin]) unless params[:fecha_fin].blank?
  end

  def estudiantes_estado
    curso_id = params[:curso_id]
    #@estudiantes = Persona.joins(:matriculas).where(:matriculas => {:curso_id => curso_id})
    @matriculas = Matricula.where(:curso_id => curso_id)
    
    
  end
  
  
  
  def create
    @estudio = Estudio.new(params[:estudio])
    @laboral = Laboral.new(params[:laboral])              
     
    @laboral.persona_id = current_user.persona.id
    @estudio.persona_id = current_user.persona.id
            
    if @estudio.save and @laboral.save
      redirect_to secretariasis_menu_principal_secretaria_path,  :notice => 'CURRICULUM CREADO'
    else
    render :new
    end
  end
  
     
            
   def edit 
     @estudios = Estudio.find(params[:id])
     @laborals = Laboral.find(params[:id])     
     if @estudios.persona.id and @laborals.persona.id == current_user.persona_id
     
     else
     
      :render_404  
     
       
       if @estudios.id.present? and @laborals.id.present?
       
       flash[:error] = ""
       redirect_to secretariasis_menu_principal_secretaria_path
     end         
   end
   end
   
#render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false MUESTRA MENSAJE DE ERROR DE URL INCORRECTA      
#    modelo = Modelo.find(params[:id]) rescue nil
#    redirect_to root_path if modelo.nil?
   
    
   
   
   def update
     @estudio= Estudio.find (params[:id])
     @estudio.update_attributes(params[:estudio])
     @laboral= Laboral.find (params[:id])
     @laboral.update_attributes(params[:laboral])
     redirect_to secretariasis_menu_principal_secretaria_path ,  :notice => 'CURRICULUM ACTUALIZADO'   
   end
   
   
     private
  def sort_column
    @periodos = Periodo.where('period_fech_ini LIKE ?', params[:fecha_inicio]) unless params[:fecha_inicio].blank?
    @periodos = @periodos.where('period_fech_fin LIKE ?', params[:fecha_fin]) unless params[:fecha_fin].blank?
    @periodos = Nivel.joins(:cursos => :periodo).where(:periodos => {:id => @periodos})
    Nivel.column_names.include?(params[:sort]) ? params[:sort] : "nivel_numero"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end
   
end

app/helpers/secretariasis_helper.rb
module SecretariasisHelper
end

app/views/secretariasis/buscar.erb
<h1><center>BUSCAR ESTUDIANTE</center></h1>
<%= form_tag result_buscar_path, :method => 'get' do %>
<%= "Ingrese Cedula: " %><%= text_field_tag :cedula_estudiante, nil, :class => "text_cedula_estudiante", :id => "text_cedula_estudiante", :style => "width:92px" %>
<%= submit_tag "Buscar" %>
<%end%>
<br>
<%if @estudiante.nil? == false%>
<br>
  CEDULA <%= @estudiante.pers_cedula %><br>
  NOMBRES <%= @estudiante.pers_nombre %><br>
  APELLIDOS <%= @estudiante.pers_apellido %><br>
  DIRECCION <%= @estudiante.pers_direccion %><br>
  TELEFONO1 <%= @estudiante.pers_telefono1 %><br>
  TELEFONO2 <%= @estudiante.pers_telefono2 %><br>
  CORREO ELECTRONICO <%= @estudiante.pers_email %>
<%end%>
<br/>

<%if @matricula.nil? == false%>
<br>
  CURSO: <%= @matricula.curso.nivel.nivel_numero %><br> 
  NIVEL: <%= @matricula.curso.nivel.nivele.tip_niv_nombre %><br>
  PARALELO: <%= @matricula.curso.cur_paralelo %><br>
  <%= link_to "EDITAR", edit_matr_alum_path(:estudiante=>@estudiante.id) %><br/>
<%end%>
<br/>

<%if @representante.nil? == false%>
<br>
  CEDULA <%= @representante.pers_cedula %><br>
  NOMBRES <%= @representante.pers_nombre %><br>
  APELLIDOS <%= @representante.pers_apellido %><br>
  DIRECCION <%= @representante.pers_direccion %><br>
  TELEFONO1 <%= @representante.pers_telefono1 %><br>
  TELEFONO2 <%= @representante.pers_telefono2 %><br>
<%end%>

  
<%if @estudiante.nil? == false%>
  <%if @usuario.usu_estado!='A'%>
    <%= link_to "Activar Usuario", activar_path(:estudiante=>@estudiante.id)%><br></br>
  <%end%>
<%=link_to "VALIDAR HOJA DE MATRICULA", validar_path(:estudiante=>@estudiante.id)%>

<%end%>

app/views/secretariasis/create.erb
PRODUCTO CREADO CON EXITO !!!

app/views/secretariasis/edit.erb
<h1><center>EDITE SU CURRICULUM</center></h1>

<%=form_for @estudios do |f| %>
   
<table align="center"> 
  
<tr>
  <td align="center"><font color="1038FF" SIZE="3"> NIVELES</font> </td>
  <td align="center"><font color="1038FF" SIZE="3"> INSTITUTOS QUE HA ESTUDIADO</font> </td>
  <td align="center"><font color="1038FF" SIZE="3"> TITULOS </font></td>
  <td align="center"><font color="1038FF" SIZE="3"> EXPERIENCIA LABORAL </font></td>
</tr>
  
  
  
 <tr> 
<FONT color ="#2A6913"  SIZE="3" FACE="arial">  
  <td><%=f.text_area :est_nivel, :rows => 10, :cols => 16 %></td>
  <td><%=f.text_area :est_instituto, :rows => 15, :cols => 36 %></td>  
  <td><%=f.text_area :est_titulos, :rows => 10, :cols => 16 %></td>
</FONT>


 
<%= form_for @laborals do |f| %>          
        <FONT color ="#2A6913"  SIZE="3" FACE="arial">            
          <td><%= f.text_area :rel_lab_inst_nomb, :rows => 15, :cols => 36 %></td>
        </FONT>
 </table>


<center><table><td><%=  f.submit "GUARDAR", {:style => 'color: #C31B1B'} %></td></table></center>
<%end%>                                                   
 </tr>      
<%end%>

app/views/secretariasis/edit_matr_alum.erb
SELECCIONE CURSO A MATRICULAR:
<br>
<%= form_tag update_matr_alum_path, :method => 'get' do%>
<%@cursos_last.each do |cl|%>
  <%= radio_button_tag :curso_id, cl.id %>
  <%= cl.nivel.nivel_numero %>
  <%= cl.nivel.nivele.tip_niv_nombre %>
  <%= cl.cur_paralelo %><br/>
<%end%>
<%= hidden_field_tag :estudiante_id, @persona.id %>
<%= submit_tag "Guardar"%>
<%end%>

app/views/secretariasis/estudiantes_curso.erb
  <html>
    <head>
      <script type="text/javascript" src="../javascripts/jquery-latest.js"></script> 
      <script type="text/javascript" src="../javascripts/jquery.tablesorter.js"></script>
      <script type="text/javascript" src="../javascripts/myTable.js"></script>
    </head>  



<center><h1>NOMINA DE ESTUDIANTES</h1></center>
 <table align="center" id="myTable" class="tablesorter">
   
   <thead> 
    <tr bgcolor="#03EB12">
    <th><%= link_to "ALUMNOS", "ALUMNOS"%></th>
    <th><%= link_to "NIVEL", "NIVEL"%></th>
 
    </tr>
  </thead>
  
  <tbody> 
  <tr>
   
   
  <%@estudiantes.each do |est|%>
 
   <td>
    <%= est.pers_nombre %>
    <%= est.pers_apellido %>
    <%#= est.matriculas.curso.nivel.nivel_numero %>
   </td>
  </tr>
<%end%>

 <input type=button name=print value="Imprimir" onClick="window.print()"><br><br>    
 </tbody>
 </table>

<br>
<br>

app/views/secretariasis/ind_distr.erb
<h1><center>BUSCAR POR PERIODO LECTIVO</center></h1>
<%= form_tag buscar_distributivos_path, :method => 'get' do %>
<%= "Fecha de inicio (aaaa/mm/dd): " %><%= text_field_tag :fecha_inicio, nil, :class => "text_fecha_inicio", :id => "text_fecha_inicio", :style => "width:92px" %><br/>
<%= "Fecha de fin (aaaa/mm/dd): " %><%= text_field_tag :fecha_fin, nil, :class => "text_fecha_fin", :id => "text_fecha_fin", :style => "width:92px" %>
<%= submit_tag "Buscar" %>
<%end%>

app/views/secretariasis/ind_estud.erb
<center><h1>BUSCAR ESTUDIANTES POR PERIODO LECTIVO</h1></center> <br/>
<%= form_tag buscar_estudiantes_path, :method => 'get' do %>
<%= "Fecha de inicio (aaaa/mm/dd): " %><%= text_field_tag :fecha_inicio, nil, :class => "text_fecha_inicio", :id => "text_fecha_inicio", :style => "width:92px" %><br/>
<%= "Fecha de fin (aaaa/mm/dd): " %><%= text_field_tag :fecha_fin, nil, :class => "text_fecha_fin", :id => "text_fecha_fin", :style => "width:92px" %>
<%= submit_tag "Buscar" %>
<%end%>
<br/>
<br/>

app/views/secretariasis/ind_estud_estado.erb
<h1><center>BUSCAR ESTADO DE ESTUDIANTES POR PERIODO LECTIVO</center></h1><br/>

<%= form_tag buscar_estado_path, :method => 'get' do %>
<%= "Fecha de inicio (aaaa/mm/dd): " %><%= text_field_tag :fecha_inicio, nil, :class => "text_fecha_inicio", :id => "text_fecha_inicio", :style => "width:92px" %><br/>
<%= "Fecha de fin (aaaa/mm/dd): " %><%= text_field_tag :fecha_fin, nil, :class => "text_fecha_fin", :id => "text_fecha_fin", :style => "width:92px" %>
<%= submit_tag "Buscar" %>
<%end%>
<br/>
<br/>

app/views/secretariasis/index.erb
<html>                           
  <head>
    <script type="text/javascript" src="../scripts/javascript.js"></script>    
  </head>  
  <body>       
    <div id="pagina" style="background-image: url(/assets/popis111.jpg); height: 506px; width: 1300px; border: 1px solid black;">          
      
      
<h1><center>CURRICULUM</center></h1>
<% @estudio.each do |f| %>         
  <table align="center">        
    
    <tr>
      <td align="center"><font color="1038FF" SIZE="3"><b>NIVELES</b></font></td>
      <td align="center"><font color="1038FF" SIZE="3"><b>INSTITUTOS</b></font></td>
      <td align="center"><font color="1038FF" SIZE="3"><b>TITULOS OBTENIDOS</b></font></td>
      <td align="center"><font color="1038FF" SIZE="3"><b>EXPERIENCIA LABORAL</b></font></td>
    </tr>


<td><FONT SIZE="2"><%=f.est_nivel %></FONT></td>
<td><FONT SIZE="2"><%=f.est_instituto %></FONT></td>
<td><FONT SIZE="2"><%=f.est_titulos %></FONT></td>

<%end%>  
 
<% @laboral.each do |f| %>
<td><FONT SIZE="2"><%=f.rel_lab_inst_nomb %></FONT></td>   

<tr>
<td align="center"><%= link_to "EDITAR CURRICULUM", edit_secretariasi_path(f) %></td>  
</tr>
</table>
 
<%end%>  

</div>
 </body>
 </html>

app/views/secretariasis/result_estud.erb
<html>
    <head>
      <script type="text/javascript" src="/javascript/jquery-latest.js"></script> 
      <script type="text/javascript" src="/javascript/jquery.tablesorter.js"></script>
    </head>  

<%if @periodos.nil?%>
<h1><center> "DEBE INGRESAR LOS VALORES CORRECTOS PARA PROCEDER A LA BUSQUEDA" </center></h1>
     
     <%else%>

<%@periodos.each do |p| %>
    <tr>
      <h1><center>AÑO LECTIVO DESDE <font color ="#F72525"><%= p.period_fech_ini %></font> HASTA <font color ="#F72525"><%= p.period_fech_fin %></font></center></h1></td>
    </tr>

<table align="center" id="myTable" class="tablesorter">    
   <thead> 
    <tr bgcolor="#03EB12">
    <tr>
      <th align = "center"><%= link_to "NIVEL", "NIVEL"%></th>
      <th align = "center"><%= link_to "PARALELO", "PARALELO"%></th>
      <th align = "center"><%= link_to "LISTA DE ESTUDIANTES", "LISTA DE ESTUDIANTES"%></th>
    </tr>
  </thead>    
     <tbody> 
    <tr>
  
    <%p.cursos.each do |c|%>
      
        <td align="center"><%= c.nivel.nivel_numero%> </td>
        <td align="center"><%= c.cur_paralelo%></td>
        <td><center><%= link_to "VISUALIZAR", estudiantes_curso_path(:curso_id => c.id) %></center></td>
      </tr>
    <%end%>
  <%end%>
     <input type=button name=print value="Imprimir" onClick="window.print()"><br><br>      
  </tbody>      
</table>

<%end%>
</html>